# Generated by Django 4.2.7 on 2023-11-20 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartype",
            old_name="name",
            new_name="model",
        ),
    ]
