# Generated by Django 4.2.7 on 2023-11-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0002_rename_name_cartype_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                (
                    "car",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license",
                        to="carshop.car",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Licence",
        ),
    ]
