# Generated by Django 4.2.7 on 2023-11-29 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0003_license_delete_licence"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderQuantity",
        ),
    ]
